version: "3.10"

services:
  db:
    container_name: bitwise_db
    image: postgres:15.3
    restart: always
    user: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - .env.docker:/app/.env
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_DB=POSTGRES_DB
    ports:
      - 5432:5432
    networks:
      - my-network

  pgadmin:
    container_name: bitwise_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin
      - .env.docker:/app/.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=PGADMIN_DEFAULT_PASSWORD
    ports:
      - 5051:80
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitwise_app
    hostname: app
    stdin_open: true
    expose:
      - '8000'
    volumes:
      - .env.docker:/app/.env
      - .env:/app/.env
    environment:
      - SECRET_KEY=SECRET_KEY
    depends_on:
      - db
    networks:
      - my-network
    ports:
      - '8000:8000'

  nginx:
    container_name: bitwise_nginx
    image: nginx
    hostname: nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - my-network

volumes:
  pgdata:
  pgadmin:

networks:
  my-network:
