version: "3.8"

services:
  db:
    container_name: bitwise_db
    image: postgres:15.3
    restart: always
    user: postgres
    volumes:
      - pgdata_two:/var/lib/postgresql/data
      - ./:/app/
    env_file:
      - ./.env.docker
    ports:
      - 5431:5432
    networks:
      - network

  pgadmin:
    container_name: bitwise_pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin_two:/var/lib/pgadmin
      - ./:/app/
    env_file:
      - ./.env.docker
    ports:
      - 5051:80
    networks:
      - network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bitwise_app
    hostname: app
    stdin_open: true
    expose:
      - '8000'
    volumes:
      - ./:/app/
    env_file:
      - ./.env.docker
    depends_on:
      - db
    networks:
      - network
    ports:
      - '8000:8000'

  nginx:
    container_name: bitwise_nginx
    image: nginx
    hostname: nginx
    ports:
      - '80:80'
    volumes:
      - ./docker/config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - network

volumes:
  pgdata_two:
  pgadmin_two:

networks:
  network:
